import '../models/track.dart';
import '../models/clip.dart';
import '../models/challenge.dart';
import '../models/achievement.dart';

class MockDataService {
  static const List<String> musicTags = [
    'All',
    'Piano Solo',
    'Inspirational',
    'Orchestral',
    'Jazz & Soul',
    'Live Concert',
  ];

  static const List<Track> sampleTracks = [
    Track(
      id: 'trk-1',
      title: 'Melody of the Inner Sight',
      artist: 'Blind Genius',
      duration: Duration(minutes: 3, seconds: 48),
      tag: 'Piano Solo',
      musicalKey: 'D Minor',
      bpm: 72,
      description: 'An evocative piano masterpiece composed purely through acoustic reverberation and touch sensation.',
      notes: 'Recorded in a historic reverberant cathedral, capturing natural acoustic harmonics.',
    ),
    Track(
      id: 'trk-2',
      title: 'Echoes of Triumph',
      artist: 'Blind Genius & Royal Philharmonic',
      duration: Duration(minutes: 4, seconds: 32),
      tag: 'Orchestral',
      musicalKey: 'G Major',
      bpm: 110,
      description: 'An uplifting symphonic movement celebrating overcoming visual barriers through sound mastery.',
      notes: 'Features a breathtaking crescendo between grand piano and 60-piece brass section.',
    ),
    Track(
      id: 'trk-3',
      title: 'Midnight Jazz in Darkness',
      artist: 'Blind Genius Quintet',
      duration: Duration(minutes: 5, seconds: 12),
      tag: 'Jazz & Soul',
      musicalKey: 'B Flat Minor',
      bpm: 96,
      description: 'Velvety jazz chords and expressive improvisation that paints pictures across the imagination.',
      notes: 'Recorded live without sheet music, improvised entirely by ear and collective intuition.',
    ),
    Track(
      id: 'trk-4',
      title: 'Light Within the Soundwaves',
      artist: 'Blind Genius',
      duration: Duration(minutes: 3, seconds: 15),
      tag: 'Inspirational',
      musicalKey: 'F Major',
      bpm: 84,
      description: 'Warm and comforting piano harmonics crafted specifically for sound therapy and relaxation.',
      notes: 'Tuned to 432 Hz for deep resonant calm.',
    ),
    Track(
      id: 'trk-5',
      title: 'Live at Carnegie Hall: Cadenza',
      artist: 'Blind Genius',
      duration: Duration(minutes: 6, seconds: 20),
      tag: 'Live Concert',
      musicalKey: 'A Minor',
      bpm: 135,
      description: 'A standing-ovation performance featuring intricate polyrhythmic arpeggios and thunderous applause.',
      notes: 'Carnegie Hall solo debut. Recorded live in New York.',
    ),
    Track(
      id: 'trk-6',
      title: 'Harmonic Awakening',
      artist: 'Blind Genius',
      duration: Duration(minutes: 4, seconds: 05),
      tag: 'Piano Solo',
      musicalKey: 'E Major',
      bpm: 78,
      description: 'Gentle morning sonata with delicate counterpoint melodies.',
      notes: 'Written on a Steinway Concert Grand Model D.',
    ),
    Track(
      id: 'trk-7',
      title: 'Whispers in the Rain',
      artist: 'Blind Genius feat. Sarah Lin',
      duration: Duration(minutes: 4, seconds: 45),
      tag: 'Jazz & Soul',
      musicalKey: 'C Minor',
      bpm: 88,
      description: 'Soulful duet merging acoustic piano and cello in heartfelt storytelling.',
      notes: 'Studio collaboration dedicated to the international day of persons with disabilities.',
    ),
  ];

  static const List<ClipItem> sampleClips = [
    ClipItem(
      id: 'clip-1',
      title: 'How I See the World Through Sound',
      duration: Duration(minutes: 5, seconds: 18),
      category: 'Mini-Documentary',
      description: 'Blind Genius explains echolocation, pitch recognition, and visualizing melodies.',
      hasAudioDescription: true,
      visualDescription: 'Blind Genius sits at a polished Steinway grand piano, smiling and tapping the keys. B-roll footage shows him navigating city streets using echolocation clicks.',
      transcript: 'When I touch the keyboard, darkness disappears. Every chord creates a vibrant geometry in my mind that is brighter than sunlight. Here is how I translate spatial awareness into harmonies...',
    ),
    ClipItem(
      id: 'clip-2',
      title: 'Masterclass: Improvise with No Sheet Music',
      duration: Duration(minutes: 7, seconds: 42),
      category: 'Tutorial',
      description: 'Techniques for ear training, muscle memory, and feeling chord changes without visual notation.',
      hasAudioDescription: true,
      visualDescription: 'Close-up on hands dancing swiftly across black and white keys, followed by an over-the-shoulder angle demonstrating finger placement.',
      transcript: 'Welcome to this masterclass. Throw away the idea that you need eyes to understand harmony. Your ears can perceive subtle frequency shifts faster than eyes can read notes on a staff...',
    ),
    ClipItem(
      id: 'clip-3',
      title: 'Carnegie Hall Standing Ovation Reaction',
      duration: Duration(minutes: 3, seconds: 55),
      category: 'Behind the Scenes',
      description: 'Emotional moments backstage following the sold-out Carnegie Hall solo concert.',
      hasAudioDescription: true,
      visualDescription: 'The backstage corridor buzzing with excitement. Blind Genius hugs his mentor and family, tears of joy reflecting stage spotlights.',
      transcript: 'The acoustic warmth of three thousand people holding their breath between the piano cadenzas was an experience I will never forget...',
    ),
    ClipItem(
      id: 'clip-4',
      title: 'Blindfolding the Philharmonic Orchestra',
      duration: Duration(minutes: 6, seconds: 10),
      category: 'Experiment',
      description: 'An acoustic experiment where 40 orchestra musicians played blindfolded to deepen listening.',
      hasAudioDescription: true,
      visualDescription: 'Violinists, cellists, and percussionists wearing black silk blindfolds, leaning in to listen intently to each other during a Bach concerto.',
      transcript: 'When visual cues disappear, the ensemble stops watching the baton and begins breathing together as a single organism...',
    ),
  ];

  static const List<Challenge> sampleChallenges = [
    Challenge(
      id: 'chal-1',
      title: 'Feel the Rhythm: Blindfolded Beat Test',
      difficulty: 'Beginner',
      deadline: 'Ends in 4 days',
      reward: 'Exclusive Gold Audio Badge & Feedback',
      description: 'Listen to a rhythmic audio prompt and record your response using hand claps or tap gestures without looking at the screen.',
      instructions: '1. Put your phone face down.\n2. Tap the start tone.\n3. Repeat the 3 rhythmic patterns by tapping on your device or desk.\n4. Screen reader will announce your accuracy score.',
      participantsCount: 328,
    ),
    Challenge(
      id: 'chal-2',
      title: 'Improvise in C Minor: 30-Second Jam',
      difficulty: 'Intermediate',
      deadline: 'Ends in 8 days',
      reward: 'Feature in Blind Genius Community Podcast',
      description: 'Compose or hum an emotional 30-second melody over our provided acoustic backing track.',
      instructions: '1. Listen to the 30-second backing loop.\n2. Record your audio track via microphone or MIDI.\n3. Submit with your audio title and inspiration story.',
      participantsCount: 194,
    ),
    Challenge(
      id: 'chal-3',
      title: 'Acoustic Navigation Soundwalk',
      difficulty: 'All Levels',
      deadline: 'Active Ongoing',
      reward: 'Accessibility Champion Trophy',
      description: 'Record ambient sounds of your neighborhood and describe what auditory cues tell you where you are.',
      instructions: 'Capture everyday sounds (chirping birds, reverberant alleys, footsteps) and explain how sound tells stories.',
      participantsCount: 512,
    ),
  ];

  static const List<CommunityEvent> sampleEvents = [
    CommunityEvent(
      id: 'evt-1',
      title: 'Global Live Audio Stream: Autumn Recital',
      date: 'Saturday, November 14',
      time: '19:00 UTC (8:00 PM CET)',
      format: 'Binaural 3D Audio Stream',
      locationOrPlatform: 'Blind Genius Live Channel',
      description: 'Experience a live virtual concert recorded in binaural spatial audio. Headphone listening recommended for immersive 360-degree acoustic stage presence.',
      isRegistered: true,
    ),
    CommunityEvent(
      id: 'evt-2',
      title: 'Interactive Q&A: Assistive Tech in Music Production',
      date: 'Thursday, November 26',
      time: '17:30 UTC',
      format: 'Live Audio Panel & Audience Chat',
      locationOrPlatform: 'Blind Genius Audio Stage',
      description: 'Discussion with leading blind audio engineers on using DAWs, screen readers like TalkBack/VoiceOver, and accessible synthesizer controls.',
      isRegistered: false,
    ),
    CommunityEvent(
      id: 'evt-3',
      title: 'World Accessibility Day Masterclass',
      date: 'Sunday, December 06',
      time: '15:00 UTC',
      format: 'Hands-on Online Workshop',
      locationOrPlatform: 'Accessible Stream Room',
      description: 'Special workshop celebrating accessibility in arts and empowering next-generation visually impaired creators.',
      isRegistered: false,
    ),
  ];

  static const List<Achievement> sampleAchievements = [
    Achievement(
      year: '2025',
      title: 'Global Accessibility Cultural Ambassador',
      organization: 'United Nations UNESCO Arts Initiative',
      description: 'Honored for pioneering accessible music experiences and championing universal digital access for blind artists across 45 nations.',
      iconType: 'trophy',
    ),
    Achievement(
      year: '2024',
      title: 'Carnegie Hall Solo Debut & Standing Ovation',
      organization: 'Carnegie Hall Foundation, New York',
      description: 'Performed a critically acclaimed sold-out solo piano recital featuring original compositions and classical sonatas.',
      iconType: 'music',
    ),
    Achievement(
      year: '2023',
      title: '50 Million Global Acoustic Streams',
      organization: 'International Streaming Alliance',
      description: 'Reached over 50 million listeners worldwide with purely instrumental piano and binaural acoustic releases.',
      iconType: 'chart',
    ),
    Achievement(
      year: '2022',
      title: 'Golden Lyre for Instrumental Composition',
      organization: 'European Music Laureates',
      description: 'Awarded first place for the orchestral symphony "Echoes of Triumph", composed entirely without visual notation.',
      iconType: 'star',
    ),
    Achievement(
      year: '2020',
      title: 'Assistive Tech Innovation in Arts Award',
      organization: 'Accessible Technology Forum',
      description: 'Recognized for co-developing haptic tactile feedback protocols for digital keyboard controllers.',
      iconType: 'verified',
    ),
  ];
}
