import '../models/track.dart';
import '../models/clip.dart';
import '../models/challenge.dart';
import '../models/achievement.dart';

class MockDataService {
  static const List<String> musicTags = [
    'همه', 'تکنوازی پیانو', 'موسیقی عرفانی', 'آهنگسازی و ارکسترال', 'انرژی‌بخش و صبحگاهی', 'آرامش‌بخش و امبینت', 'شعر و دکلمه',
  ];

  static final List<Track> sampleTracks = [
    Track(
      id: 'msg-2',
      telegramMessageId: 2,
      title: 'The Golden Dawn (طلوع طلایی)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 2, seconds: 16),
      tag: 'آرامش‌بخش و امبینت',
      tags: const [],
      description: 'سلام مخاطبین عزیز کانال. هر چند ساعتهای زیادی از طلوع طلایی خورشید میگذره. اما این قطعه با اسم طلوع طلایی تقدیم به شما. با آرزوی روزی سرشار از آرامش. ساخته شده توسط نابغه نابینا\n@blind_genius1',
      filename: 'The Golden Dawn.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/The.Golden.Dawn.mp3',
      telegramLink: 'https://t.me/blind_genius1/2',
    ),
    Track(
      id: 'msg-3',
      telegramMessageId: 3,
      title: 'آی آدم‌ها (دکلمه نگین فرهادی - موسیقی نابغه نابینا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 57),
      tag: 'شعر و دکلمه',
      tags: const [],
      description: 'سلام صبح زیباتون بخیر این دکلمه باهمه ی حس زیباش تقدیم به شما عزیزان \nگوینده:نگین فرهادی \nموسیقی ، تنظیم و تدوین : نابغه ی نابینا \n @Blind_genius1',
      filename: 'آي-آدمها.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.1-audio/ai-adamha.mp3',
      telegramLink: 'https://t.me/blind_genius1/3',
    ),
    Track(
      id: 'msg-4',
      telegramMessageId: 4,
      title: 'The Easternmost Night of the Earth (شرقی‌ترین شب زمین)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 8),
      tag: 'انرژی‌بخش و صبحگاهی',
      tags: const [],
      description: 'سلام و شب بخیر خدمت مخاطبین عزیزمون. امیدوارم که توی این شرایط عجیب در بهترین حالی باشید که میشه. متأسفانه امروز از صبح نتونستم در کانال پستی رو منتشر کنم اما الآن با جدید ترین قطعه بچه های تیم نابغه نابینا به اسم شرقی ترین شب زمین به دیدار تون اومدم.\nامیدوارم که این قطعه رو دوست داشته باشید و دوستانی که کار تنظیم یا تدوین انجام میدن بتونند ازش توی کار ها شون استفاده کنند. همچنین بگم این کار هیچ کپی رایتی نداره و برای استفاده در اینستاگرام یا یوتیوب کاملا مناسبه.\nخوشحال میشم برای دوستانتون هم بفرستید و اونها رو به کانالمون دعوت کنید.\n@blind_genius1',
      filename: 'The easternmost night of the earth (Blind Genius ).mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/The.easternmost.night.of.the.earth.Blind.Genius.mp3',
      telegramLink: 'https://t.me/blind_genius1/4',
    ),
    Track(
      id: 'msg-6',
      telegramMessageId: 6,
      title: 'ای عاشقان - نسخه اول (Ey Aasheghan - Version 1)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 6, seconds: 1),
      tag: 'موسیقی عرفانی',
      tags: const [],
      description: 'این نسخه اول.\n@blind_genius1',
      filename: 'reservedclicktrack2205 – ey-aasheghan - 04.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.1-audio/ey-aasheghan-v1.mp3',
      telegramLink: 'https://t.me/blind_genius1/6',
    ),
    Track(
      id: 'msg-7',
      telegramMessageId: 7,
      title: 'ای عاشقان - نسخه دوم (Ey Aasheghan - Version 2)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 6, seconds: 8),
      tag: 'موسیقی عرفانی',
      tags: const [],
      description: 'این هم نسخه دوم\n@blind_genius1',
      filename: 'reservedclicktrack2205 – ey-aasheghan - 04.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.1-audio/ey-aasheghan-v2.mp3',
      telegramLink: 'https://t.me/blind_genius1/7',
    ),
    Track(
      id: 'msg-9',
      telegramMessageId: 9,
      title: 'Whisper of Hope (زمزمه امید)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 9),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام و عرض ادب خدمت مخاطبین عزیز. امیدوارم که خوب باشید.\nروزگار بسیار عجیبی بر همه مون میگذره. بین کلی استرس و دغدغه و مسائل درگیری و هر چیز که فکرش رو بکنید گیر افتادیم. خسته و رونده، مغز ها مون تیر میکشه، صورتی مون خاکستر نشین شده و ناله العطشمون به فرات لب اونی که باید برسه نمیرسه.\nاما وقتی یک مدت با خودت تنها میشی و به نوای دلت گوش میکنی یکی تو عمیق ترین قسمت قلبت هست که میگه: اوضاع همیشه هم انقدر بد نمیمونه. به قول معین: این زندگی این جور نمیمونه. عشق من ازم دور نمیمونه. صاحب داره دنیا همه کاراش. اینجوری که ناجور نمیمونه.\nدقیقا با گوش دادن به همین ندای درونی یک قطعه ساختیم برای شما مخاطبین عزیز به اسم زمزمه امید. امیدوارم دوستش داشته باشید. نظر و ری اکشن فراموش نشه.\nهمچنین این قطعه هم بدون کپیرایت هست و میتونید با ذکر منبع ازش داخل تدوین ها، پیج ها و جاهای مختلف استفاده کنید.\nWhisper of hope a new track composed by: BlindGenius\nکانال ما رو به دوستانتون معرفی کنید.\nبه امید روز های بهتر\n@blind_genius1',
      filename: 'Whisper of Hope - 02.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/Whisper.of.Hope.-.02.mp3',
      telegramLink: 'https://t.me/blind_genius1/9',
    ),
    Track(
      id: 'msg-12',
      telegramMessageId: 12,
      title: 'Pleasant Morning (صبح دلپذیر)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 9),
      tag: 'انرژی‌بخش و صبحگاهی',
      tags: const [],
      description: 'سلام دوستان.\nصبح همگی بخیر.\nیه وقتایی مشکلات زندگی٫ تنهایی هاش٫ غمها و سؤالاتی که در بعضی از حوزه های اون به وجود میاد جوری انرژیتو میگیره و حواستو به خودش پرت میکنه که حس میکنی هیچ تعلق خاطری به این دنیا نداری.\nدیگه برات فرق نمیکنه چی پیش بیاد و چی بشه.\nمن یه چند روزی دوچار چنین حالتی بودم. اما. الان اومدم تا با یک موسیقی که حال و هوای گرم جنگلهای آفریقا رو تدایی میکنه همراه با ریتم پر جنبوجوش و پر انرژیش به امید خدا به استقبال یک روز پر انرژی بریم.\nترک جدیدم به اسم صبح دلپذیر تقدیم به شما خوبان.\n\n\nA new track called pleasant morning composed by Blind genius is available\nEnjoy listening\nکانال ما را با دوستان خود به اشتراک بگذارید\n@Blind_genius1',
      filename: 'pleasant morning.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/pleasant.morning.mp3',
      telegramLink: 'https://t.me/blind_genius1/12',
    ),
    Track(
      id: 'msg-13',
      telegramMessageId: 13,
      title: 'Starry Night (شب پر ستاره)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 24),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام و شب بخیر دوستان عزیز. خیلی خیلی ممنونیم که با وجود کم شدن فعالیت های کانال ما رو همراهی میکنید. به امید شب هایی پر از ستاره قطعه شب پر ستاره رو تقدیم حضورتون میکنیم. خوشحال میشیم نظرات تون رو داخل دایرکت بهمون بگید.\na new track called starry night composed by: Blind Genius is available, enjoy and share it.\nکانال ما رو به عزیزان تون معرفی کنید. میتونید برای تدوین ها، پیج ها و ویدیو ها تون از موزیک ها مون استفاده کنید.\nشاد باشید و شب تون آروم.\n@blind_genius1',
      filename: 'starry night.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/starry.night.mp3',
      telegramLink: 'https://t.me/blind_genius1/13',
    ),
    Track(
      id: 'msg-14',
      telegramMessageId: 14,
      title: 'شور کاروان (Shur Caravan)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 13),
      tag: 'موسیقی عرفانی',
      tags: const [],
      description: 'سلام و عرض ادب خدمت همه دوستان. وقتتون بخیر. امیدوارم که خوب باشید. راستش این سری هیچ حرف یا سخنی رو واسه گفتن ندارم.\nفقط امیدوارم از این قطعه خوشتون بیاد. جالبیش اینه که هنوز اسمی هم واسش انتخاب نکردم.\nخوشحال میشم بر اساس حال و هوای قطعه اسامی که دوست دارین رو در دایرکت بهم پیشنهاد بدین.\nموفق و شاد باشید.\nکانال ما رو هم به دوستان تون معرفی کنید.\n@blind_genius1',
      filename: 'Shur Caravan-1785654712390.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/Shur.Caravan-1785654712390.mp3',
      telegramLink: 'https://t.me/blind_genius1/14',
    ),
    Track(
      id: 'msg-15',
      telegramMessageId: 15,
      title: 'تو بزن تا من برقصم (تنظیم جَز برزیلی - سلیمان هاشمی‌زاده)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 2, seconds: 21),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'اگه کار تو بزن تا من برقصم خانم مهستی قرار بود جَز تنظیم بشه و تو برزیل اجرا بشه این طوری میشد.\n\nگوش کنید و لذت ببرید از زندگی.\nتنظیم سلیمان هاشمی زاده.\nکانال ما رو به عزیزان تون معرفی کنید تا توی این شرایط سخت بتونیم با هم دیگه کمی از زندگی لذت ببریم.\n@blind_genius1',
      filename: 'to-bezan-ta-man-beraghsam-01.0.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/to-bezan-ta-man-beraghsam-01.0.mp3',
      telegramLink: 'https://t.me/blind_genius1/15',
    ),
    Track(
      id: 'msg-16',
      telegramMessageId: 16,
      title: 'فرنگیس (پیانو: سلیمان هاشمی‌زاده - سیاوش قمیشی)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 13),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام خدمت مخاطبین عزیز کانال مون. امشب آهنگ بسیار زیبای فرنگیس رو براتون آماده کردیم تا با آرامش زیباش خواب آروم و زیبایی رو تجربه کنید.\nقطعه فرنگیس، خواننده: سیاوش قمیشی\nنوازنده پیانو: سلیمان هاشمی زاده.\nکانال ما رو به دوستان تون معرفی کنید\n@blind_genius1',
      filename: 'farangis-siavash-ghomeishi.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/farangis-siavash-ghomeishi.mp3',
      telegramLink: 'https://t.me/blind_genius1/16',
    ),
    Track(
      id: 'msg-17',
      telegramMessageId: 17,
      title: 'عروسک جون (پیانو: سلیمان هاشمی‌زاده - بانو هایده)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 7),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'با سلام و شب بخیر.\nمخاطبین عزیز، امشب یکی از جاودانه های موسیقی ایران رو براتون آوردیم به اسم عروسک جون..\nخواننده این اثر بانو هایده هستند و نوازنده پیانو با احترام سلیمان هاشمی زاده.\nکانال ما رو به دوستان تون معرفی کنید.\nشب به همگی خوش\n@blind_genius1',
      filename: 'banoo-haydeh-aroosakjoon.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/banoo-haydeh-aroosakjoon.mp3',
      telegramLink: 'https://t.me/blind_genius1/17',
    ),
    Track(
      id: 'msg-18',
      telegramMessageId: 18,
      title: 'نیاز (فریدون فروغی)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 5),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: '@blind_genius1',
      filename: 'fereydoon-forooghi-niaz.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/fereydoon-forooghi-niaz.mp3',
      telegramLink: 'https://t.me/blind_genius1/18',
    ),
    Track(
      id: 'msg-19',
      telegramMessageId: 19,
      title: 'Forest Ambience (فضای جنگل)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 14),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'با سلام خدمت عزیزان.\nشبتون بخیر.\nقطعه جدید تیم نابغه نابینا به اسم forest_ambience تقدیم به شما.\nاین قطعه بدون کپیرایت هست و داخل تدوینها، تنظیمها، و جاهایی که نیاز به موسیقی بدون کپیرایت هست میتونید ازش استفاده کنید.\nشب خوبی داشته باشید.\nکانال ما رو به دوستان خودتون معرفی کنید:\n@Blind_genius1',
      filename: 'forest-ambience-01.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/forest-ambience-01.mp3',
      telegramLink: 'https://t.me/blind_genius1/19',
    ),
    Track(
      id: 'msg-20',
      telegramMessageId: 20,
      title: 'هله عاشقان بکوشید (مولانا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 4, seconds: 54),
      tag: 'موسیقی عرفانی',
      tags: const [],
      description: '☀️ سلام عزیزان، صبحتون بخیر…\n\nصبح رو با یک حس تازه شروع کنیم؟ 🎧\nاین بار «مولانا» رو از زاویه‌ای دیگر بشنوید؛ شاید این موسیقی، حرفی تازه برای دلِ شما داشته باشه.\n\n🎶 «هله عاشقان بکوشید…»\n\nحالا شما بگید؛\nاگر بخواید حالِ این موسیقی رو فقط با یک کلمه توصیف کنید، اون کلمه چیه؟ 👇🏻\n\n🎧 گوش کنید، حسش کنید و کلمه‌تون رو برام بنویسید…\n\nو اگر فکر می‌کنید این موزیک می‌تونه حالِ یکی از دوستاتون رو خوب کنه، کانال Blind Genius رو بهش معرفی کنید. ❤️\n@Blind_genius1',
      filename: 'hele-aasheqan-bekooshid-05.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/hele-aasheqan-bekooshid-05.mp3',
      telegramLink: 'https://t.me/blind_genius1/20',
    ),
    Track(
      id: 'msg-21',
      telegramMessageId: 21,
      title: 'Stranger in This World (غریبه‌ای در این دنیا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 26),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: '☀️ صبح بخیر همراهان عزیز\n«روزها فکر من این است و همه شب سخنم...»\nصبح‌تون رو با این ملودی آرامش‌بخش و نوای آشنای روح شروع کنید. بگذارید موسیقی امروز رو برای شما عمیق‌تر و زیباتر کنه. 🌿✨\nقطعه ای جدید از: Blind Genius\n🎧 بشنوید، آرامش بگیرید و برای عزیزانتون بفرستید.\n🆔 @Blind_genius1',
      filename: 'Stranger in This World-05.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/Stranger.in.This.World-05.mp3',
      telegramLink: 'https://t.me/blind_genius1/21',
    ),
    Track(
      id: 'msg-22',
      telegramMessageId: 22,
      title: 'Infinite Presence (حضور بی‌نهایت)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 2),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام دوستان عزیز. امیدوارم که خوب باشید. این کار با نهایت دل و جون تقدیم به شما. انشا الله که گوش کنید و حس و حال دلتون خوب بشه.\nاگه خواستید ری اکشن هم فراموش نشه.\nکانال مون هم لطف میکنید به دوستان تون معرفی کنید\n@blind_genius1',
      filename: 'Infinite Presence-04.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/Infinite.Presence-04.mp3',
      telegramLink: 'https://t.me/blind_genius1/22',
    ),
    Track(
      id: 'msg-23',
      telegramMessageId: 23,
      title: 'به که ماند؟ (Like Who? - مولانا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 0),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام دوستان عزیز. کار به که ماند؟ آهنگ جدید نابغه نابینا با متنی از حضرت مولانا تقدیم به شما عزیزان.\n@Blind_genius1',
      filename: 'like-who_-21 (1).mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/like-who_-21.1.mp3',
      telegramLink: 'https://t.me/blind_genius1/23',
    ),
    Track(
      id: 'msg-27',
      telegramMessageId: 27,
      title: 'Corner Store Glow (مجموعه نابغه نابینا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 1, seconds: 53),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام، صبح زیباتون بخیر ☀️\nگاهی یک قطعه موسیقی می‌تواند هم‌زمان ریشه‌های دلتنگی را لمس کند و روح انسان را به پرواز درآورد.\nدر این پست، شنونده‌ی اثر تازه‌ای از مجموعه «نابغه نابینا» هستید؛ قطعه‌ای شورانگیز که با آوازی اصیل و لحنی نوستالژیک آغاز می‌شود و سپس با ریتمی گرم، رقصان و مدیترانه‌ای ادامه می‌یابد تا روشنی و امید را به لحظه‌های بامداد شما هدیه کند.\nاگر از شنیدن این اثر لذت بردید، آن را با دوستانی که برای شروع روزشان به نغمه‌ای انرژی‌بخش نیاز دارند به اشتراک بگذارید تا این حالِ خوب، سهم بقیه هم بشود.\n🆔 @blind_genius1\n#موسیقی #آهنگ_جدید #صبح_بخیر #نابغه_نابینا #موزیک_شاد',
      filename: 'Corner Store Glow.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/Corner.Store.Glow.mp3',
      telegramLink: 'https://t.me/blind_genius1/27',
    ),
    Track(
      id: 'msg-36',
      telegramMessageId: 36,
      title: 'مرا عهدیست با شادی (مولانا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 4, seconds: 49),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'در این آخرای فصل تابستون که کم کم داریم وارد فصل پاییز میشیم و باید نگران ریزش برگها، میوه ها و گذشت عمر باشیم، چه قدر خوبه که به قول مولانا با شادی عهد ببندیم که شادی از آن ما باشد.\nاین قطعه دلنشین رو دقیقا روی همین شعر ساختم، گوش کنید و لذت ببرید و اگه براتون جذاب بود، خوشحال میشم کانال ما رو به دوستان تون معرفی کنید.\n@Blind_genius1',
      filename: 'mara-ahdist-ba-shadi(Blind genius).mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/mara-ahdist-ba-shadi.Blind.genius.mp3',
      telegramLink: 'https://t.me/blind_genius1/36',
    ),
    Track(
      id: 'msg-37',
      telegramMessageId: 37,
      title: 'تو خورشیدی و یا زهره (سلیمان هاشمی‌زاده)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 4, seconds: 22),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'گاهی یک ملودی و چند بیت شعر، آرامشی عمیق‌تر از هزار واژه به دل می‌بخشند... 🕊️✨\nاین قطعه‌ی شنیدنی بر روی غزلی عرفانی و شورانگیز، با آهنگسازی هنرمندانه و احساسی «سلیمان هاشمی‌زاده» (blind genius) خلق شده است. درهم‌آمیزی لحن اصیل با نوای گیرای سازها و آواز، فضایی روح‌نواز و سرشار از خلسه و معنا به این اثر بخشیده است.\nاگر این اولین باری است که آثار ما را می‌شنوید، به جمع ما بپیوندید و این قطعه را با عزیزانتان و عاشقان موسیقی اصیل به اشتراک بگذارید.\n🆔 @Blind_genius1\n#سلیمان_هاشمی_زاده #موسیقی_سنتی #آهنگسازی #موسیقی_عرفانی',
      filename: 'to-khorshidi-vaya-zohre-03.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/to-khorshidi-vaya-zohre-03.mp3',
      telegramLink: 'https://t.me/blind_genius1/37',
    ),
    Track(
      id: 'msg-38',
      telegramMessageId: 38,
      title: 'جای دیگر نمیشود (بی تو به سر نمیشود - مولانا)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 2, seconds: 32),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'صبح تون بخیر مخاطبین عزیز. گزیده ای از غزل زیبای بی تو به سر نمیشود از حضرت مولانا، تقدیم به شما نازنینان.\nکانال ما رو به دوستانتون معرفی کنید\n@Blind_genius1',
      filename: 'جای دیگر نمیشود.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/default.mp3',
      telegramLink: 'https://t.me/blind_genius1/38',
    ),
    Track(
      id: 'msg-40',
      telegramMessageId: 40,
      title: 'به خداحافظی تلخ تو (فاضل نظری)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 13),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام و درود خدمت همه عزیزان.\nشب تون بخیر.\nخیلی دلم واستون تنگ شده بود.\nاین دفعه براتون یک قطعه آوردم با شعری از فاضل نظری ولی با سبکی کاملا متفاوت.\nامیدوارم خوشتون بیاد\nکانال ما رو با رفیقاتون به اشتراک بذارید\n@blind_genius1',
      filename: 'be-khodahafeziye-talkhe-to.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/be-khodahafeziye-talkhe-to.mp3',
      telegramLink: 'https://t.me/blind_genius1/40',
    ),
    Track(
      id: 'msg-41',
      telegramMessageId: 41,
      title: 'پروانه (شعر هما میرافشار)',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 4, seconds: 9),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلام روز بخیر خدمت مخاطبین عزیز.\nامیدوارم که خوب باشید.\nاین قطعه با شعری از بانوی ترانه ایران خانم هما میر افشار تقدیم به شما مهربانان\nروز و روزگار بر همگی خوش.\n@Blind_genius1\n#پروانه #بانو_ترانه_ایران #هما_میرافشار #نابغه_نابینا',
      filename: 'parvane.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.0-audio/parvane.mp3',
      telegramLink: 'https://t.me/blind_genius1/41',
    ),
    Track(
      id: 'msg-43',
      telegramMessageId: 43,
      title: 'آهنگ بی قرار از معین با نوازندگی نابغه نابینا',
      artist: 'سلیمان هاشمی‌زاده (نابغه نابینا)',
      duration: const Duration(minutes: 3, seconds: 36),
      tag: 'تکنوازی پیانو',
      tags: const [],
      description: 'سلاااااام عزیزای دل.\nهمون طوری که وعده داده بودیم، یک کار جانانه از استاد معین عزیز براتون آماده کردیم.\nقطعه بیقرار از استاد معین بزرگوار با نوازندگی: سلیمان هاشمی زاده (blind genius)\nکانال ما رو با دوستان خوبتون به اشتراک بذارید\n@Blind_genius1\n#معین #معین_بیقرار #بیقرار #موزیک #نوستالژی #سلیمان_هاشمی_زاده #نوازندگی #blind_genius',
      filename: 'moin-bigharar.mp3',
      streamUrl: 'https://github.com/blind-genius/blind-genius-app/releases/download/v1.0.2-audio/moin-bigharar.mp3',
      telegramLink: 'https://t.me/blind_genius1/43',
    ),
  ];

  static List<Track> get tracks => sampleTracks;

  static const List<ClipItem> sampleClips = [
    ClipItem(
      id: 'clip-1',
      title: 'How I "See" the Piano: A Blind Virtuoso Explains',
      duration: Duration(minutes: 5, seconds: 12),
      category: 'Inspiration',
      description: 'An intimate studio conversation on how tactile memory, ear training, and mental visualization guide virtuosic performances.',
      hasAudioDescription: true,
      visualDescription: 'Blind Genius sitting at a grand piano in warm stage light, demonstrating acoustic spatial awareness by gently hovering hands over keys.',
      transcript: 'When I touch the keyboard, darkness disappears. Every chord creates a vibrant geometry in my mind that is brighter than sunlight. Here is how I translate spatial awareness into harmonies...',
    ),
    ClipItem(
      id: 'clip-2',
      title: 'Masterclass: Improvise with No Sheet Music',
      duration: Duration(minutes: 7, seconds: 42),
      category: 'Tutorial',
      description: 'Techniques for ear training, muscle memory, and feeling chord changes without visual notation.',
      hasAudioDescription: true,
      visualDescription: 'Close-up on hands dancing swiftly across black and white keys, followed by an over-the-shoulder angle demonstrating finger placement.',
      transcript: 'Welcome to this masterclass. Throw away the idea that you need eyes to understand harmony. Your ears can perceive subtle frequency shifts faster than eyes can read notes on a staff...',
    ),
    ClipItem(
      id: 'clip-3',
      title: 'Carnegie Hall Standing Ovation Reaction',
      duration: Duration(minutes: 3, seconds: 55),
      category: 'Behind the Scenes',
      description: 'Emotional moments backstage following the sold-out Carnegie Hall solo concert.',
      hasAudioDescription: true,
      visualDescription: 'The backstage corridor buzzing with excitement. Blind Genius hugs his mentor and family, tears of joy reflecting stage spotlights.',
      transcript: 'The acoustic warmth of three thousand people holding their breath between the piano cadenzas was an experience I will never forget...',
    ),
    ClipItem(
      id: 'clip-4',
      title: 'Blindfolding the Philharmonic Orchestra',
      duration: Duration(minutes: 6, seconds: 10),
      category: 'Experiment',
      description: 'An acoustic experiment where 40 orchestra musicians played blindfolded to deepen listening.',
      hasAudioDescription: true,
      visualDescription: 'Violinists, cellists, and percussionists wearing black silk blindfolds, leaning in to listen intently to each other during a Bach concerto.',
      transcript: 'When visual cues disappear, the ensemble stops watching the baton and begins breathing together as a single organism...',
    ),
  ];

  static const List<Challenge> sampleChallenges = [
    Challenge(
      id: 'chal-1',
      title: 'Feel the Rhythm: Blindfolded Beat Test',
      difficulty: 'Beginner',
      deadline: 'Ends in 4 days',
      reward: 'Exclusive Gold Audio Badge & Feedback',
      description: 'Listen to a rhythmic audio prompt and record your response using hand claps or tap gestures without looking at the screen.',
      instructions: '1. Put your phone face down.\n2. Tap the start tone.\n3. Repeat the 3 rhythmic patterns by tapping on your device or desk.\n4. Screen reader will announce your accuracy score.',
      participantsCount: 328,
    ),
    Challenge(
      id: 'chal-2',
      title: 'Improvise in C Minor: 30-Second Jam',
      difficulty: 'Intermediate',
      deadline: 'Ends in 8 days',
      reward: 'Feature in Blind Genius Community Podcast',
      description: 'Compose or hum an emotional 30-second melody over our provided acoustic backing track.',
      instructions: '1. Listen to the 30-second backing loop.\n2. Record your audio track via microphone or MIDI.\n3. Submit with your audio title and inspiration story.',
      participantsCount: 194,
    ),
    Challenge(
      id: 'chal-3',
      title: 'Acoustic Navigation Soundwalk',
      difficulty: 'All Levels',
      deadline: 'Active Ongoing',
      reward: 'Accessibility Champion Trophy',
      description: 'Record ambient sounds of your neighborhood and describe what auditory cues tell you where you are.',
      instructions: 'Capture everyday sounds (chirping birds, reverberant alleys, footsteps) and explain how sound tells stories.',
      participantsCount: 512,
    ),
  ];

  static const List<CommunityEvent> sampleEvents = [
    CommunityEvent(
      id: 'evt-1',
      title: 'Global Live Audio Stream: Autumn Recital',
      date: 'Saturday, November 14',
      time: '19:00 UTC (8:00 PM CET)',
      format: 'Binaural 3D Audio Stream',
      locationOrPlatform: 'Blind Genius Live Channel',
      description: 'Experience a live virtual concert recorded in binaural spatial audio. Headphone listening recommended for immersive 360-degree acoustic stage presence.',
      isRegistered: true,
    ),
    CommunityEvent(
      id: 'evt-2',
      title: 'Interactive Q&A: Assistive Tech in Music Production',
      date: 'Thursday, November 26',
      time: '17:30 UTC',
      format: 'Live Audio Panel & Audience Chat',
      locationOrPlatform: 'Blind Genius Audio Stage',
      description: 'Discussion with leading blind audio engineers on using DAWs, screen readers like TalkBack/VoiceOver, and accessible synthesizer controls.',
      isRegistered: false,
    ),
    CommunityEvent(
      id: 'evt-3',
      title: 'World Accessibility Day Masterclass',
      date: 'Sunday, December 06',
      time: '15:00 UTC',
      format: 'Hands-on Online Workshop',
      locationOrPlatform: 'Accessible Stream Room',
      description: 'Special workshop celebrating accessibility in arts and empowering next-generation visually impaired creators.',
      isRegistered: false,
    ),
  ];

  static const List<Achievement> sampleAchievements = [
    Achievement(
      year: '2025',
      title: 'Global Accessibility Cultural Ambassador',
      organization: 'United Nations UNESCO Arts Initiative',
      description: 'Honored for pioneering accessible music experiences and championing universal digital access for blind artists across 45 nations.',
      iconType: 'trophy',
    ),
    Achievement(
      year: '2024',
      title: 'Carnegie Hall Solo Debut & Standing Ovation',
      organization: 'Carnegie Hall Foundation, New York',
      description: 'Performed a critically acclaimed sold-out solo piano recital featuring original compositions and classical sonatas.',
      iconType: 'music',
    ),
    Achievement(
      year: '2023',
      title: '50 Million Global Acoustic Streams',
      organization: 'International Streaming Alliance',
      description: 'Reached over 50 million listeners worldwide with purely instrumental piano and binaural acoustic releases.',
      iconType: 'chart',
    ),
    Achievement(
      year: '2022',
      title: 'Golden Lyre for Instrumental Composition',
      organization: 'European Music Laureates',
      description: 'Awarded first place for the orchestral symphony "Echoes of Triumph", composed entirely without visual notation.',
      iconType: 'star',
    ),
    Achievement(
      year: '2020',
      title: 'Assistive Tech Innovation in Arts Award',
      organization: 'Accessible Technology Forum',
      description: 'Recognized for co-developing haptic tactile feedback protocols for digital keyboard controllers.',
      iconType: 'verified',
    ),
  ];
}
